name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Display API key
        run:
          echo "API Key"

      - name: Replace CLIENT_ID placeholder
        run: |
          sed -i "s|FIREBASE_API_KEY|'${{ secrets.FIREBASE_API_KEY }}'|g" auth.html
          sed -i "s|process\.env\.FIREBASE_AUTH_DOMAIN|'${{secrets.FIREBASE_AUTH_DOMAIN}}'|g" auth.html
          sed -i "s|process\.env\.FIREBASE_PROJECT_ID|'${{secrets.FIREBASE_PROJECT_ID}}'|g" auth.html
          sed -i "s|process\.env\.FIREBASE_STORAGE_BUCKET|'${{secrets.FIREBASE_STORAGE_BUCKET}}'|g" auth.html
          sed -i "s|process\.env\.FIREBASE_MESSAGING_SENDER_ID|'${{secrets.FIREBASE_MESSAGING_SENDER_ID}}'|g" auth.html
          sed -i "s|process\.env\.FIREBASE_APP_ID|'${{secrets.FIREBASE_APP_ID}}'|g" auth.html
          sed -i "s|process\.env\.FIREBASE_MEASUREMENT_ID|'${{secrets.FIREBASE_MEASUREMENT_ID}}'|g" auth.html
          sed -i "s|process\.env\.CLIENT_ID|'${{secrets.CLIENT_ID}}'|g" auth.html
