name: Example Workflow

on:
  push:
    branches: [ main ]

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        env:
          TEST: ${{ secrets.FIREBASE_API_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Display API key
        run:
          echo "API Key"
          pwd
          ls

      - name: Replace CLIENT_ID placeholder
        run: |
          sed -i "s/ENV_FIREBASE_API_KEY/${{ env.TEST }}/g" auth.html
