name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}  # Using environment secrets
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Replace CLIENT_ID placeholder
        run: |
          sed -i '' -e "s|process\.env\.FIREBASE_API_KEY|FIREBASE_API_KEY|g" auth.html
          sed -i '' -e "s|process\.env\.FIREBASE_AUTH_DOMAIN|${FIREBASE_AUTH_DOMAIN}|g" auth.html
          sed -i '' -e "s|process\.env\.FIREBASE_PROJECT_ID|'${FIREBASE_PROJECT_ID}'|g" auth.html
          sed -i '' -e "s|process\.env\.FIREBASE_STORAGE_BUCKET|'${FIREBASE_STORAGE_BUCKET}'|g" auth.html
          sed -i '' -e "s|process\.env\.FIREBASE_MESSAGING_SENDER_ID|'${FIREBASE_MESSAGING_SENDER_ID}'|g" auth.html
          sed -i '' -e "s|process\.env\.FIREBASE_APP_ID|'${FIREBASE_APP_ID}'|g" auth.html
          sed -i '' -e "s|process\.env\.FIREBASE_MEASUREMENT_ID|'${FIREBASE_MEASUREMENT_ID}'|g" auth.html
          sed -i '' -e "s|process\.env\.CLIENT_ID|'${CLIENT_ID}'|g" auth.html
